### ISSUE TITLE
Fresh install fails to compile

### ISSUE THREAD

**Issue by delaneyj** [wmonk/cra-ts-scratch#1]
```
git clone https://github.com/wmonk/cra-ts-scratch
yarn install
yarn start
```

> Error: Cannot find module 'webpack-hot-middleware'

`yarn add webpack-hot-middleware`

> Error in ./src/index.tsx
> (3,30): error TS2307: Cannot find module 'react-hot-loader'.

`yarn add react-hot-loader`

> (3,30): error TS7016: Could not find a declaration file for module 'react-hot-loader'. 'cra-ts-scratch\nod
> e_modules\react-hot-loader\index.js' implicitly has an 'any' type.

> Error in ./src/index.tsx
> (18,12): error TS2339: Property 'hot' does not exist on type 'NodeModule'.
> 
> Error in ./src/index.tsx
> (19,12): error TS2339: Property 'hot' does not exist on type 'NodeModule'.
> 
> Error in ./src/index.tsx
> (20,25): error TS2346: Supplied parameters do not match any signature of call target.
> 
> Error in ./src/App.tsx
> (4,14): error TS2346: Supplied parameters do not match any signature of call target.

**Comment by wmonk** [comment]
This isn't really meant to be used, was more an example for [this issue](https://github.com/wmonk/create-react-app-typescript/issues/3) to show how to implement it. I have pushed a commit to add the correct dependencies, please pull and try again.
